//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string SeoTitle { get; set; }
        public string ImageURL { get; set; }
        public string SiteURL { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string ContentText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
